name: traffic-control
extensions:
- name: dapr
  components-path: "./dapr/components/"

services:
- name: FineCollectionService
  project: FineCollectionService/FineCollectionService.csproj
  bindings:
    - protocol: http
      port: 6001

- name: Simulation
  project: Simulation/Simulation.csproj

- name: TrafficControlService
  project: TrafficControlService/TrafficControlService.csproj
  bindings:
    - protocol: http
      port: 6000

- name: VehicleRegistrationService
  project: VehicleRegistrationService/VehicleRegistrationService.csproj
  bindings:
    - protocol: http
      port: 6002

- name: dtc-rabbitmq
  image: rabbitmq:3-management
  bindings:
    - port: 15672
      name: admin-web
    - port: 5672
      name: rabbitmq
